[book]
title = "Вероятность и статистика (v. 2026.0)"
authors = ["evavoronkova"]
language = "ru"
src = "src"
description = "Заметки и задачи по вероятности и статистике"


[build]
build-dir = "book"

[output.html]
no-section-label = true
additional-css = [
    "theme/css/custom.css",
    "theme/css/figures.css",
    "theme/css/problems.css",
]

additional-js = [
    "theme/js/figures.js"
]


mathjax-support = false

[output.html.fold]
enable = true
level = 2

[output.html.print]
enable = true

[output.html.search]
enable = true
limit-results = 30
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor.katex]
command = "mdbook-katex"
after = ["links"]


[preprocessor.footnote]



