[book]
title = "Вероятность и статистика"
authors = ["evavoronkova"]
language = "ru"
src = "src"
description = "Заметки и задачи по вероятности и статистике"


[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = false

[output.html.fold]
enable = true
level = 2

[output.html.print]
enable = true

[output.html.search]
enable = true
limit-results = 30
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor.katex]
command = "./mdbook-katex.exe"
after = ["links"]
